services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./htpasswd:/tmp/htpasswd
    ports:
      - "80:80"
    depends_on:
      - grafana

